fix: use openclaw-gateway network for cli
During docker-setup workflow, the openclaw-cli container does not work
with the openclaw-gateway container with below error:

```
 Error: gateway closed (1006 abnormal closure (no close frame)): no close reason
 Gateway target: ws://127.0.0.1:18789
 Source: local loopback
```

This is because the openclaw-cli container is started as a new one and
can not connect to the gateway container by localhost::18789.
By setting the `network_mode: "service:openclaw-gateway"`, it will use
the same network of the container and thus is capable of connecting to
the gateway.

Tested: Verify below command works fine for docker setup:

```
 docker compose run --rm openclaw-cli health
```

Signed-off-by: Lei YU <mine260309@gmail.com>